/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MarkPagePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var http = __toESM(require("http"));
var DEFAULT_SETTINGS = {
  markPageUrl: "https://markpage.timikays.us.kg",
  autoOpenBrowser: true,
  defaultTheme: "",
  serverPort: 3001
};
var pendingConfig = null;
var pendingExport = null;
var pendingGetState = false;
var currentState = {};
var lastExportResult = null;
var MarkPagePlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.server = null;
  }
  async onload() {
    await this.loadSettings();
    this.startLocalServer();
    this.addRibbonIcon("send", "\u53D1\u9001\u5230 MarkPage", async () => {
      await this.syncToMarkPage();
    });
    this.addCommand({
      id: "sync-to-markpage",
      name: "\u53D1\u9001\u5F53\u524D\u7B14\u8BB0\u5230 MarkPage",
      checkCallback: (checking) => {
        const active = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        if (!active)
          return false;
        if (!checking)
          this.syncToMarkPage();
        return true;
      }
    });
    this.addCommand({
      id: "sync-to-markpage-pick-theme",
      name: "\u9009\u62E9\u4E3B\u9898\u540E\u53D1\u9001\u5230 MarkPage",
      checkCallback: (checking) => {
        const active = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        if (!active)
          return false;
        if (!checking)
          new ThemePickerModal(this.app, this).open();
        return true;
      }
    });
    this.addSettingTab(new MarkPageSettingTab(this.app, this));
    console.log("MarkPage Sync plugin loaded");
  }
  onunload() {
    this.stopLocalServer();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // ─── Local HTTP Server ──────────────────────────────────────────────────
  startLocalServer() {
    if (this.server)
      return;
    const port = this.settings.serverPort;
    const plugin = this;
    this.server = http.createServer((req, res) => {
      res.setHeader("Access-Control-Allow-Origin", "*");
      res.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
      res.setHeader("Access-Control-Allow-Headers", "Content-Type");
      if (req.method === "OPTIONS") {
        res.writeHead(204);
        res.end();
        return;
      }
      const url = new URL(req.url || "/", `http://localhost:${port}`);
      if (req.method === "GET" && url.pathname === "/vault-image") {
        const vaultPath = url.searchParams.get("p");
        if (!vaultPath) {
          res.writeHead(400, { "Content-Type": "application/json" });
          res.end(JSON.stringify({ error: "Missing p parameter" }));
          return;
        }
        const file = plugin.app.vault.getAbstractFileByPath(vaultPath);
        if (!file || !(file instanceof import_obsidian.TFile)) {
          res.writeHead(404, { "Content-Type": "application/json" });
          res.end(JSON.stringify({ error: "File not found: " + vaultPath }));
          return;
        }
        const ext = file.extension.toLowerCase();
        const mimeMap = {
          png: "image/png",
          jpg: "image/jpeg",
          jpeg: "image/jpeg",
          gif: "image/gif",
          webp: "image/webp",
          svg: "image/svg+xml",
          bmp: "image/bmp"
        };
        const mime = mimeMap[ext];
        if (!mime) {
          res.writeHead(415, { "Content-Type": "application/json" });
          res.end(JSON.stringify({ error: "Not an image file" }));
          return;
        }
        plugin.app.vault.readBinary(file).then((binary) => {
          res.writeHead(200, {
            "Content-Type": mime,
            "Cache-Control": "public, max-age=3600"
          });
          res.end(Buffer.from(binary));
        }).catch(() => {
          res.writeHead(500, { "Content-Type": "application/json" });
          res.end(JSON.stringify({ error: "Failed to read file" }));
        });
        return;
      }
      if (url.pathname === "/health") {
        res.writeHead(200, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ status: "ok" }));
        return;
      }
      if (req.method === "GET" && url.pathname === "/api/mcp/poll") {
        const response = {};
        if (pendingConfig) {
          response.config = pendingConfig;
          pendingConfig = null;
        }
        if (pendingExport) {
          response.export = pendingExport;
          pendingExport = null;
        }
        if (pendingGetState) {
          response.getState = true;
          pendingGetState = false;
        }
        res.writeHead(200, { "Content-Type": "application/json" });
        res.end(JSON.stringify(response));
        return;
      }
      if (req.method === "POST" && url.pathname === "/api/mcp/config") {
        let body = "";
        req.on("data", (chunk) => {
          body += chunk;
        });
        req.on("end", () => {
          try {
            pendingConfig = JSON.parse(body);
            res.writeHead(200, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ success: true }));
          } catch (e) {
            res.writeHead(400, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ success: false, error: "Invalid JSON" }));
          }
        });
        return;
      }
      if (req.method === "POST" && url.pathname === "/api/mcp/export") {
        let body = "";
        req.on("data", (chunk) => {
          body += chunk;
        });
        req.on("end", () => {
          try {
            const data = JSON.parse(body);
            pendingExport = { scale: data.scale || 2, format: data.format || "png" };
            res.writeHead(200, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ success: true }));
          } catch (e) {
            res.writeHead(400, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ success: false, error: "Invalid JSON" }));
          }
        });
        return;
      }
      if (req.method === "POST" && url.pathname === "/api/mcp/export-result") {
        let body = "";
        req.on("data", (chunk) => {
          body += chunk;
        });
        req.on("end", () => {
          try {
            lastExportResult = JSON.parse(body);
          } catch (e) {
          }
          res.writeHead(200, { "Content-Type": "application/json" });
          res.end(JSON.stringify({ success: true }));
        });
        return;
      }
      if (req.method === "POST" && url.pathname === "/api/mcp/state") {
        let body = "";
        req.on("data", (chunk) => {
          body += chunk;
        });
        req.on("end", () => {
          try {
            currentState = JSON.parse(body);
          } catch (e) {
          }
          res.writeHead(200, { "Content-Type": "application/json" });
          res.end(JSON.stringify({ success: true }));
        });
        return;
      }
      if (req.method === "GET" && url.pathname === "/api/mcp/state") {
        res.writeHead(200, { "Content-Type": "application/json" });
        res.end(JSON.stringify(currentState));
        return;
      }
      res.writeHead(404);
      res.end("Not found");
    });
    this.server.listen(port, () => {
      console.log(`MarkPage Sync: local server on port ${port}`);
    });
    this.server.on("error", (err) => {
      console.error("MarkPage Sync server error:", err);
      new import_obsidian.Notice(`\u672C\u5730\u670D\u52A1\u542F\u52A8\u5931\u8D25: ${err.message}`);
    });
  }
  stopLocalServer() {
    if (this.server) {
      this.server.close();
      this.server = null;
    }
  }
  restartLocalServer() {
    this.stopLocalServer();
    this.startLocalServer();
  }
  // ─── Core: Sync ──────────────────────────────────────────────────────────
  async syncToMarkPage(overrideTheme) {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!activeView) {
      new import_obsidian.Notice("\u6CA1\u6709\u6253\u5F00\u7684\u7B14\u8BB0");
      return;
    }
    const file = activeView.file;
    if (!file) {
      new import_obsidian.Notice("\u627E\u4E0D\u5230\u5F53\u524D\u6587\u4EF6");
      return;
    }
    new import_obsidian.Notice("\u6B63\u5728\u53D1\u9001\u5230 MarkPage...");
    try {
      let markdown = await this.app.vault.read(file);
      markdown = await this.processImages(markdown, file);
      const config = { markdown };
      if (overrideTheme || this.settings.defaultTheme) {
        config.themeId = overrideTheme || this.settings.defaultTheme;
      }
      const titleMatch = markdown.match(/^#\s+(.+)$/m);
      if (titleMatch) {
        config.coverConfig = {
          enabled: true,
          title: titleMatch[1].trim()
        };
      }
      pendingConfig = config;
      if (this.settings.autoOpenBrowser) {
        this.openMarkPage();
      }
      new import_obsidian.Notice("\u2705 \u5DF2\u53D1\u9001\u5230 MarkPage\uFF01");
    } catch (error) {
      console.error("MarkPage sync error:", error);
      new import_obsidian.Notice(`\u274C \u53D1\u9001\u5931\u8D25: ${error.message}`);
    }
  }
  // ─── Image Processing ────────────────────────────────────────────────────
  //
  // Obsidian 有两种图片格式：
  //   1. Wikilink: ![[image.png]] 或 ![[image.png|300]]
  //   2. 标准 Markdown: ![alt text](path/to/image.png)
  //
  // 核心思路：不塞 base64，而是把 vault 路径编码成短 URL
  // 浏览器 <img> 标签从插件本地 HTTP 服务加载图片
  // 同一张 vault 图片只保留一次，避免重复
  async processImages(markdown, sourceFile) {
    var _a;
    const sourceDir = ((_a = sourceFile.parent) == null ? void 0 : _a.path) || "";
    const baseUrl = `http://localhost:${this.settings.serverPort}`;
    const processedFiles = /* @__PURE__ */ new Set();
    let imageCount = 0;
    let failCount = 0;
    const failedNames = [];
    const wikiLinkRegex = /!\[\[([^\]]+\.(png|jpg|jpeg|gif|webp|svg|bmp))(?:\|([^\]]*))?\]\]/gi;
    const wikiMatches = [...markdown.matchAll(wikiLinkRegex)];
    for (const match of wikiMatches) {
      const fullMatch = match[0];
      const imageName = match[1];
      const sizeHint = match[3] || "";
      try {
        const imageFile = this.findImageFile(imageName);
        if (imageFile) {
          if (processedFiles.has(imageFile.path)) {
            markdown = markdown.replace(fullMatch, "");
            continue;
          }
          processedFiles.add(imageFile.path);
          const imageUrl = `${baseUrl}/vault-image?p=${encodeURIComponent(imageFile.path)}`;
          const altText = sizeHint ? `${imageName}|${sizeHint}` : imageName;
          markdown = markdown.replace(fullMatch, `![${altText}](${imageUrl})`);
          imageCount++;
        } else {
          failCount++;
          failedNames.push(imageName);
        }
      } catch (e) {
        failCount++;
        failedNames.push(imageName);
      }
    }
    const mdImageRegex = /!?\[([^\]]*)\]\(([^)]+)\)/gi;
    const mdMatches = [...markdown.matchAll(mdImageRegex)];
    for (const match of mdMatches) {
      const fullMatch = match[0];
      const alt = match[1];
      const imagePath = match[2];
      const isImage = fullMatch.startsWith("!");
      if (imagePath.startsWith("http") || imagePath.startsWith("data:") || imagePath.startsWith("app://") || imagePath === "")
        continue;
      const decodedPath = decodeURIComponent(imagePath);
      if (!isImage && !/\.(png|jpg|jpeg|gif|webp|svg|bmp)$/i.test(decodedPath))
        continue;
      try {
        const imageFile = this.resolveLocalImage(decodedPath, sourceDir) || this.findImageFile(decodedPath);
        if (imageFile) {
          if (processedFiles.has(imageFile.path)) {
            markdown = markdown.replace(fullMatch, "");
            continue;
          }
          processedFiles.add(imageFile.path);
          const imageUrl = `${baseUrl}/vault-image?p=${encodeURIComponent(imageFile.path)}`;
          markdown = markdown.replace(fullMatch, `![${alt}](${imageUrl})`);
          imageCount++;
        }
      } catch (e) {
        console.error(`MarkPage Sync: failed to process image ${imagePath}:`, e);
      }
    }
    if (imageCount > 0 && failCount === 0) {
      new import_obsidian.Notice(`\u{1F4F7} \u5DF2\u5904\u7406 ${imageCount} \u5F20\u56FE\u7247`);
    } else if (failCount > 0) {
      new import_obsidian.Notice(`\u26A0\uFE0F ${imageCount} \u5F20\u56FE\u7247\u6210\u529F\uFF0C${failCount} \u5F20\u672A\u627E\u5230: ${failedNames.join(", ")}`);
    }
    return markdown;
  }
  findImageFile(imageName) {
    const files = this.app.vault.getFiles();
    const lowerName = imageName.toLowerCase();
    let found = files.find((f) => f.name.toLowerCase() === lowerName);
    if (found)
      return found;
    found = files.find((f) => f.path.toLowerCase().endsWith("/" + lowerName) || f.path.toLowerCase().endsWith("\\" + lowerName));
    if (found)
      return found;
    found = files.find(
      (f) => f.path.toLowerCase().includes(lowerName) && /\.(png|jpg|jpeg|gif|webp|svg|bmp)$/i.test(f.path)
    );
    return found || null;
  }
  resolveLocalImage(imagePath, sourceDir) {
    let fullPath = imagePath;
    if (fullPath.startsWith("./"))
      fullPath = fullPath.substring(2);
    if (!fullPath.startsWith("/")) {
      fullPath = (0, import_obsidian.normalizePath)(`${sourceDir}/${fullPath}`);
    } else {
      fullPath = (0, import_obsidian.normalizePath)(fullPath.substring(1));
    }
    const af = this.app.vault.getAbstractFileByPath(fullPath);
    return af instanceof import_obsidian.TFile ? af : null;
  }
  openMarkPage() {
    const mcpUrl = `http://localhost:${this.settings.serverPort}`;
    const fullUrl = `${this.settings.markPageUrl}?mcpUrl=${encodeURIComponent(mcpUrl)}`;
    window.require("electron").shell.openExternal(fullUrl);
  }
};
var AVAILABLE_THEMES = [
  { id: "minimal-white", name: "\u6781\u7B80\u767D", emoji: "\u{1F90D}" },
  { id: "dark-night", name: "\u6697\u591C\u9ED1", emoji: "\u{1F5A4}" },
  { id: "tech-blue", name: "\u79D1\u6280\u84DD", emoji: "\u{1F499}" },
  { id: "sakura-pink", name: "\u6A31\u82B1\u7C89", emoji: "\u{1F338}" },
  { id: "cosmic-purple", name: "\u5B87\u5B99\u7D2B", emoji: "\u{1F49C}" },
  { id: "cyberpunk", name: "\u8D5B\u535A\u670B\u514B", emoji: "\u{1F9BE}" },
  { id: "forest-green", name: "\u68EE\u6797\u7EFF", emoji: "\u{1F49A}" },
  { id: "sunset-orange", name: "\u65E5\u843D\u6A59", emoji: "\u{1F9E1}" },
  { id: "ocean-blue", name: "\u6D77\u6D0B\u84DD", emoji: "\u{1F30A}" },
  { id: "retro-paper", name: "\u590D\u53E4\u7EB8\u5F20", emoji: "\u{1F4DC}" }
];
var ThemePickerModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u9009\u62E9\u4E3B\u9898" });
    for (const theme of AVAILABLE_THEMES) {
      const btn = contentEl.createEl("button", {
        text: `${theme.emoji} ${theme.name}`
      });
      btn.style.cssText = `
				display:block;width:100%;margin:8px 0;padding:12px 16px;
				text-align:left;font-size:14px;cursor:pointer;
				border:1px solid var(--background-modifier-border);
				border-radius:6px;background:var(--background-secondary);
				color:var(--text-normal);transition:all .15s ease;
			`;
      btn.addEventListener("click", () => {
        this.close();
        this.plugin.syncToMarkPage(theme.id);
      });
      btn.addEventListener("mouseenter", () => {
        btn.style.transform = "translateX(4px)";
      });
      btn.addEventListener("mouseleave", () => {
        btn.style.transform = "none";
      });
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var MarkPageSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "MarkPage \u540C\u6B65\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("MarkPage \u7F51\u5740").setDesc("MarkPage \u7F51\u9875\u5730\u5740\uFF0C\u522B\u4EBA\u4E5F\u80FD\u7528\u540C\u4E00\u4E2A\u5730\u5740").addText((text) => text.setPlaceholder("https://markpage.timikays.us.kg").setValue(this.plugin.settings.markPageUrl).onChange(async (value) => {
      this.plugin.settings.markPageUrl = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u9ED8\u8BA4\u4E3B\u9898").setDesc("\u540C\u6B65\u65F6\u81EA\u52A8\u5E94\u7528\u7684\u4E3B\u9898\uFF08\u53EF\u9009\uFF09").addDropdown((dropdown) => {
      dropdown.addOption("", "\u4E0D\u6307\u5B9A");
      for (const t of AVAILABLE_THEMES) {
        dropdown.addOption(t.id, `${t.emoji} ${t.name}`);
      }
      dropdown.setValue(this.plugin.settings.defaultTheme).onChange(async (value) => {
        this.plugin.settings.defaultTheme = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("\u81EA\u52A8\u6253\u5F00\u6D4F\u89C8\u5668").setDesc("\u540C\u6B65\u540E\u81EA\u52A8\u5728\u6D4F\u89C8\u5668\u6253\u5F00 MarkPage").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoOpenBrowser).onChange(async (value) => {
      this.plugin.settings.autoOpenBrowser = value;
      await this.plugin.saveSettings();
    }));
  }
};
